In [1]:
import torch

In [2]:
torch.cuda.is_available()

False

In [3]:
a = torch.ones(3)

In [4]:
a

tensor([1., 1., 1.])

In [6]:
a[1], float(a[1])

(tensor(1.), 1.0)

In [7]:
points = torch.tensor([[1, 4], [2, 1], [3, 5]])

In [8]:
points

tensor([[1, 4],
        [2, 1],
        [3, 5]])

In [9]:
points.shape

torch.Size([3, 2])

In [10]:
points = torch.FloatTensor([[1, 4], [2, 1], [3, 5]])

In [12]:
points[0,1]

tensor(4.)

In [13]:
points.storage()

/var/folders/hz/qyzbs8kd6dl2nctjx5cgg9mm0000gn/T/ipykernel_24576/2396954748.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [14]:
points_storage = points.storage()

In [15]:
points_storage

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [16]:
points_storage[0] = 2

In [17]:
points

tensor([[2., 4.],
        [2., 1.],
        [3., 5.]])

In [18]:
second_point = points[1]

In [20]:
second_point.storage_offset()

2

In [21]:
second_point.size()

torch.Size([2])

In [22]:
second_point.shape

torch.Size([2])

In [23]:
points.stride()

(2, 1)

In [2]:
double_points = torch.ones(10, 2, dtype = torch.double)

In [3]:
double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [4]:
points = torch.randn(10, 2)

In [5]:
short_points = points.type(torch.short)

In [6]:
id(points.storage())

/var/folders/hz/qyzbs8kd6dl2nctjx5cgg9mm0000gn/T/ipykernel_2763/398353280.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  id(points.storage())


4695572000

In [7]:
id(short_points.storage())

4695570272

In [8]:
points = torch.ones(3,4)

points_np = points.numpy()

points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [11]:
torch.save(points, "points.t")

In [12]:
with open("points2.t", "wb") as f:
    torch.save(points, f)

In [13]:
points = torch.load("points.t")

In [15]:
import h5py

In [16]:
f = h5py.File("../points.hdf5", "w")
dset = f.create_dataset("coords", data = points.numpy())
f.close()

In [17]:
f = h5py.File("../points.hdf5", "r")
dset = f["coords"]
last_points = dset[1:]

In [18]:
last_points

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [19]:
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### exercise

In [20]:
a = torch.tensor(list(range(9)))

In [25]:
a.size(), a.storage_offset(), a.stride()

(torch.Size([9]), 0, (1,))

In [26]:
b = a.view(3, 3)

In [27]:
b[1, 1]

tensor(4)

In [28]:
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [29]:
c = b[1:, 1:]

In [30]:
c

tensor([[4, 5],
        [7, 8]])

In [31]:
c.size(), c.storage_offset(), c.stride()

(torch.Size([2, 2]), 4, (3, 1))

In [42]:
c = c.to(dtype = torch.float)

In [43]:
c.sqrt_()

tensor([[2.0000, 2.2361],
        [2.6458, 2.8284]])